### ISSUE TITLE
add nodeId as a response header

### ISSUE THREAD

**Issue by gruns** [filecoin-project/saturn-node#16]
for now, `saturn-pop` like

```
saturn-pop: <nodeId>
```

we shouldn't use the `X-` prefix, eg no `x-saturn-pop`; that's deprecated. see https://www.rfc-editor.org/rfc/rfc6648

in the future, we'll add additional response headers. like cache hit/miss status. cloudflare does this:

```
$ curl -I "https://imgflip.com/i/6eqsf6" | grep -i status
cf-cache-status: HIT
```

of note for context: the ipfs gws already include a number of headers. ex:

```
$ curl -I "https://ipfs.io/ipfs/Qme7ss3ARVgxv6rXqVPiikMJ8u2NLgmgszg13pYrDKEoiu" | grep -i ipfs
x-ipfs-gateway-host: ipfs-bank16-sv15
x-ipfs-path: /ipfs/Qme7ss3ARVgxv6rXqVPiikMJ8u2NLgmgszg13pYrDKEoiu
x-ipfs-pop: ipfs-bank16-sv15
x-ipfs-lb-pop: gateway-bank1-sv15
```

**Comment by DiegoRBaquero** [comment]
does it affect cors at all? @guanzo

**Comment by guanzo** [comment]
ya, need to have `access-control-expose-headers: saturn-pop` for cross origin JS to access it.
